name: "HifiGan"
sample_rate: 22050
n_fft: 1024
fmax: null
pad_value: -11.52
train_dataset: ???
validation_datasets: ???
n_mels: 80

model:
  train_ds:
    dataset:
      _target_: "nemo.collections.tts.data.datalayers.AudioDataset"
      manifest_filepath: ${train_dataset}
      max_duration: null
      min_duration: 0.75
      n_segments: 16384
      trim: false
    dataloader_params:
      drop_last: false
      shuffle: true
      batch_size: 32
      num_workers: 4

  validation_ds:
    dataset:
      _target_: "nemo.collections.tts.data.datalayers.AudioDataset"
      manifest_filepath: ${validation_datasets}
      max_duration: null
      min_duration: 0.75
      n_segments: -1
      trim: false
    dataloader_params:
      drop_last: false
      shuffle: false
      batch_size: 1
      num_workers: 4

  preprocessor:
    _target_: nemo.collections.asr.parts.features.FilterbankFeatures
    dither: 0.0
    frame_splicing: 1
    nfilt: ${n_mels}
    highfreq: ${fmax}
    log: true
    log_zero_guard_type: clamp
    log_zero_guard_value: 1e-05
    lowfreq: 0
    mag_power: 1.0
    n_fft: ${n_fft}
    n_window_size: 1024
    n_window_stride: 256
    normalize: null
    pad_to: 0
    pad_value: ${pad_value}
    preemph: null
    sample_rate: ${sample_rate}
    stft_exact_pad: true
    stft_conv: false
    window: hann

  optim:
    lr: 0.0002
    adam_b1: 0.8
    adam_b2: 0.99
    lr_decay: 0.999

  generator:
    _target_: nemo.collections.tts.modules.hifigan_modules.Generator
    resblock: 1
    upsample_rates: [8,8,2,2]
    upsample_kernel_sizes: [16,16,4,4]
    upsample_initial_channel: 512
    resblock_kernel_sizes: [3,7,11]
    resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]
  
trainer:
  gpus: -1 # number of gpus
  max_epochs: ???
  num_nodes: 1
  accelerator: ddp
  accumulate_grad_batches: 1
  checkpoint_callback: False  # Provided by exp_manager
  logger: False  # Provided by exp_manager
  log_every_n_steps: 100
  check_val_every_n_epoch: 1

exp_manager:
  exp_dir: null
  name: ${name}
  create_tensorboard_logger: false
  create_checkpoint_callback: True

  version: ???
  use_datetime_version: false
  resume_if_exists: true
  resume_ignore_no_checkpoint: true
  
  create_wandb_logger: true
  wandb_logger_kwargs:
    project: hifi
    name: hifi_name
