name: &name "UniGlow"
sample_rate: 22050
n_mels: 80
pad_value: -11.52
train_dataset: ???
validation_datasets: ???
resume_from_ckpt: null

model:
  sigma: 1.0
  train_ds:
    dataset:
      _target_: "nemo.collections.tts.data.datalayers.AudioDataset"
      manifest_filepath: ${train_dataset}
      max_duration: null
      min_duration: 0.1
      n_segments: 16384
      trim: false
    dataloader_params:
      drop_last: false
      shuffle: true
      batch_size: 12
      num_workers: 4

  validation_ds:
    dataset:
      _target_: "nemo.collections.tts.data.datalayers.AudioDataset"
      manifest_filepath: ${validation_datasets}
      max_duration: null
      min_duration: 0.1
      n_segments: 49152   # 3 secs
      trim: false
    dataloader_params:
      drop_last: false
      shuffle: false
      batch_size: 12
      num_workers: 4

  preprocessor:
    _target_: nemo.collections.asr.parts.features.FilterbankFeatures
    dither: 0
    frame_splicing: 1
    nfilt: ${n_mels}
    log: true
    log_zero_guard_type: clamp
    log_zero_guard_value: 1e-05
    lowfreq: 0
    highfreq: 8000
    mag_power: 1.0
    sample_rate: ${sample_rate}
    n_fft: 1024
    n_window_size: 1024
    n_window_stride: 256
    normalize: null
    pad_to: 0 #16
    pad_value: ${pad_value}
    preemph: null
    stft_conv: false
    stft_exact_pad: false
    window: hann

  n_flows: 12
  n_group: 8
  n_mel_channels: ${n_mels}
  n_wn_channels: 256
  n_wn_layers: 8
  wn_kernel_size: 3

  adv_loss_coef: 0
  fm_loss: false

  nll_loss: 
    _target_: nemo.collections.tts.losses.uniglowloss.NllLoss
  nll_loss_coef: 1.0

  stft_loss:
    _target_: nemo.collections.tts.losses.uniglowloss.MultiResolutionSTFTLoss
    fft_sizes: [64, 128, 256, 512, 1024, 2048, 4096]
    hop_sizes: [32, 64, 128, 256, 512, 1024, 2048]
    win_lengths: [64, 128, 256, 512, 1024, 2048, 4096]
  stft_loss_coef: 1.0

  optimizer:
    _target_: torch.optim.Adam
    lr: 1e-4
    betas: [0.8, 0.999]
    amsgrad: true

trainer:
  gpus: -1 # number of gpus
  max_epochs: ???
  num_nodes: 1
  accelerator: ddp
  accumulate_grad_batches: 1
  checkpoint_callback: False  # Provided by exp_manager
  logger: False  # Provided by exp_manager
  precision: 32
  automatic_optimization: false
  num_sanity_val_steps: 0

exp_manager:
  exp_dir: null
  name: *name
  create_tensorboard_logger: True
  create_checkpoint_callback: True
  checkpoint_callback_params:
    monitor: val_stoi
    save_top_k: 3
    mode: max
